version: 1.0.{build}
build:
  verbosity: minimal
image: Visual Studio 2019
branches:
  only:
    - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Hahn.ApplicatonProcess.May2020.Data/Hahn.ApplicatonProcess.May2020.Data.csproj --verbosity m
  - cmd: dotnet restore ./Hahn.ApplicatonProcess.May2020.Domain/Hahn.ApplicatonProcess.May2020.Domain.csproj --verbosity m
  - cmd: dotnet restore ./Hahn.ApplicatonProcess.May2020.Web/Hahn.ApplicatonProcess.May2020.Web.csproj --verbosity m
build_script:
  # output will be in ./Hahn.ApplicatonProcess.May2020.Web/bin/debug/netcoreapp2.0/publish
  - cmd: dotnet publish ./Hahn.ApplicatonProcess.May2020.Web/Hahn.ApplicatonProcess.May2020.Web.csproj
after_build:
  # For once the build has completed
artifacts:
  - path: '\Hahn.ApplicatonProcess.May2020.Web\bin\Debug\netcoreapp2.0\publish'
    name: WebSite
    type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./Hahn.ApplicatonProcess.Application.Tests/Hahn.ApplicatonProcess.Application.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd Hahn.ApplicatonProcess.Application.Tests
  - cmd: dotnet test
on_finish:
  # any cleanup in here
deploy: off
